trigger: none

pool: Env-agentpool

stages:
- stage: build 
  displayName : Build of Terraform init validate and plan 

  jobs:
  - job: initvalidate
    displayName : Terraform init and validate
    steps:
    - task: TerraformTask@5 # Terraform init 
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        backendServiceArm: 'raviconnection'
        backendAzureRmResourceGroupName: 'rg13'
        backendAzureRmStorageAccountName: 'stg1311'
        backendAzureRmContainerName: 'cont13'
        backendAzureRmKey: 'prod.terraform.tfstate'
    - task: TerraformTask@5 # Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'

  - job : plan
    displayName : Terraform plan 
    dependsOn: initvalidate
    steps :
    - task: TerraformTask@5 # Terraform plan 
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        environmentServiceNameAzureRM: 'raviconnection'

- stage: Scanning 
  displayName : Code Scanning 
  jobs:
  - job : scanning
    displayName : Scanning 
    steps : 
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'

- stage: deploy
  displayName: deploy of resource
  jobs :
  - job : Terrafomapply 
    steps : 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        environmentServiceNameAzureRM: 'raviconnection'






    
