trigger: none

pool: Env-agentpool

stages:
- stage: build # Satge1 
  displayName : Build of Terraform init validate and plan 

  jobs:
  - job: initvalidate
    displayName : Terraform init and validate
    steps:
    - task: TerraformTask@5 # Terraform init 
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        backendServiceArm: 'raviconnection'
        backendAzureRmResourceGroupName: 'rg13'
        backendAzureRmStorageAccountName: 'stg1311'
        backendAzureRmContainerName: 'cont13'
        backendAzureRmKey: 'prod.terraform.tfstate'
    - task: TerraformTask@5 # Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'

  - job : plan
    displayName : Terraform plan 
    dependsOn: initvalidate
    steps :
    - task: TerraformTask@5 # Terraform plan 
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        environmentServiceNameAzureRM: 'raviconnection'

- stage: Scanning # stage 2
  displayName : Code Scanning 
  jobs:
  - job : scanning
    displayName : Scanning 
    steps : 
    - task: tfsec@1 # Scanning 
      inputs:
        version: 'v1.26.0'



- stage: deploy # stage 3
  jobs:
  - job: manualvalidation
    displayName: mv of code
    pool: server
    steps:
    - task: ManualValidation@1 # manual validation
      inputs:
        notifyUsers: 'helloraviranjan99@gmail.com'
        approvers: 'helloraviranjan99@gmail.com'

  - job : Terrafomapply 
    steps: 
    - task: TerraformTask@5 # Terraform init 
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        backendServiceArm: 'raviconnection'
        backendAzureRmResourceGroupName: 'rg13'
        backendAzureRmStorageAccountName: 'stg1311'
        backendAzureRmContainerName: 'cont13'
        backendAzureRmKey: 'prod.terraform.tfstate'
    
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        environmentServiceNameAzureRM: 'raviconnection'






    
